letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
escape_char = "\\" ("\\" | "n" | "t" | "r" | "\"") ;
wspace = " " | "\n" | "\t" ;
terminal = ";"
anything = letter | digit | escape_char | wspace

variable_name = letter {letter | digit | "_"} ;

variable_term = variable_name
text_term = "\"" {anything} "\""
zero_or_one_term = "[" full_term "]"
zero_or_more_term = "{" full_term "}"
group_term = "(" full_term ")"
base_term = text_term | variable_term | zero_or_one_term | zero_or_more_term | group_term

or_term = term "|" term { "|" term}
add_term = full_term " " full_term {" " full_term}
full_term = term | or_term | add_term | terminal


lhs = variable_name
rhs = full_term
rule = lhs " = " rhs

grammar = {rule}